---
title: "Homework 1 Lucas Stormowski"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE)
```


```{r}
rm(list = ls())

library(dplyr)
library(ggplot2)
library(data.table)

z = fread("https://www.fhwa.dot.gov/bridge/nbi/2018/delimited/WI18.txt")

str(z)

sum(is.na(z))

z = select(z, STATE_CODE_001,FEATURES_DESC_006A,STRUCTURE_NUMBER_008,YEAR_BUILT_027,COUNTY_CODE_003,DETOUR_KILOS_019,TOLL_020,MAINTENANCE_021,OWNER_022,TRAFFIC_LANES_ON_028A,STRUCTURE_LEN_MT_049,PERCENT_ADT_TRUCK_109,LAT_016,LONG_017,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062, YEAR_RECONSTRUCTED_106)

z = rename(z, State_Code = STATE_CODE_001, Structure_Number = STRUCTURE_NUMBER_008, Description = FEATURES_DESC_006A, Year_Built = YEAR_BUILT_027, County_Code = COUNTY_CODE_003, Detour_Length = DETOUR_KILOS_019, Toll= TOLL_020, Deck_Condition = DECK_COND_058, Number_of_Lanes = TRAFFIC_LANES_ON_028A, Superstructure_Condition = SUPERSTRUCTURE_COND_059, Year_Reconstructed = YEAR_RECONSTRUCTED_106, Substructure_Condition = SUBSTRUCTURE_COND_060, Channel_Condition = CHANNEL_COND_061, Culvert_Condition = CULVERT_COND_062,Percent_Truck = PERCENT_ADT_TRUCK_109, Structure_Length = STRUCTURE_LEN_MT_049, Latitude = LAT_016, Longitude = LONG_017, Maintenance_Responsibility = MAINTENANCE_021, Owner = OWNER_022)

if(z$Year_Reconstructed==0){z$Year_Reconstructed = z$Year_Built}
z$Year_Reconstructed[which(z$Year_Reconstructed == 0)] = z$Year_Built

z %>%
  group_by(Year_Built) %>%
  summarize(Overall_Bridge_Condition = mean((as.numeric(Deck_Condition)+as.numeric(Superstructure_Condition)+as.numeric(Substructure_Condition)+as.numeric(Channel_Condition)), na.rm = TRUE)) %>% 
  ggplot(mapping = aes(x = Year_Built, y = Overall_Bridge_Condition)) + geom_point(alpha = 1/3)

z %>%
  group_by(Year_Reconstructed) %>%
  summarize(Overall_Bridge_Condition = mean((as.numeric(Deck_Condition)+as.numeric(Superstructure_Condition)+as.numeric(Substructure_Condition)+as.numeric(Channel_Condition)), na.rm = TRUE)) %>% 
  ggplot(mapping = aes(x = Year_Reconstructed, y = Overall_Bridge_Condition)) + geom_point(alpha = 1/3)

```
